### ISSUE TITLE
"random access" takes to long when start and end are the same and not found in bam-file

### ISSUE THREAD

**Issue by envanloo** [betteridiot/bamnostic#26]
**Faster search when start and end position in bam.fetch are the same!**

If in the "random access" mode I specify end as 1 higher than start on a position where no reads are available it goes very fast:

-------------------------------------
b=time.time()
bam = bs.AlignmentFile("my.bam", 'rb')    
for i, read in enumerate(bam.fetch(contig="my_scaffold",start=248586,end=248586+1)):
    if i >=1:
       break
    print(read)

c=time.time() 
print(c-b)

0.1510002613067627

Output: nothing, because no read found.

but when I use start =end, it takes forever:

b=time.time()
bam = bs.AlignmentFile("my.bam", 'rb')    
for i, read in enumerate(bam.fetch(contig="my scaffold",start=248586,end=248586)):
    if i >=1:
       break
    print(read)

c=time.time() 
print(c-b)

156.4850001335144

Output: nothing, because no read found.

I think somehow a search is done in the whole bam-file, which seems unnecessary. 
Since the bam-file is sorted and indexed, should it not be possible to see that once you cannot find a read overlapping the indicated position, there cannot be another read (as the file is sorted no further look ahead is necessary).

So why is there such a difference in lookup time for the two cases?

Please note my bam-file is about 4 Gbyte.

**Comment by betteridiot** [comment]
Okay, I will have to take a look at this over the weekend.

**Comment by betteridiot** [comment]
Alright, I think I may have fixed the issue. The genomic intervals that are meant to be [inclusive, exclusive). However, that assumption was never checked for fault-tolerance. You, @envanloo, helped me find that and nip it in the bud. This was causing long run times, to return nothing, because it wasn't caught by boundary checking...and was going through the rest of the file.

I have made it so that users cannot define a `start` and `stop` that are equal to each other. This is to maintain consistency with the Python language as a whole. For example:

```python
>>> a = 'abc'
>>> print(a[1:1])
''
```

**Comment by betteridiot** [comment]
Fixed by 843687b98f9ef9fdf085f871a5d098bc43cb34a7
