### ISSUE TITLE
benchmarking

### ISSUE THREAD

**Issue by leaxael** [betteridiot/bamnostic#46]
Hi, I'm trying to do some simple benchmarks. I took a small (12Mb, 603 alignments) BAM file as the input. 

For pysam, I did:

```
import pysam
from time import time
print(pysam.__version__)
f = 'in.bam'

t = time()
i = 0
samfile = pysam.AlignmentFile(f)
for read in samfile:
    a = str(read)
    i+=1
print('time:', time()-t)
print('total:', i)  # sancheck
```
For bamnostic:
```
import bamnostic as bs
from time import time
f = 'in.bam'
t = time()
i = 0
bam = bs.AlignmentFile(f, 'rb', check_sq=False)
while True:
    try: next(bam); i+=1
    except:break
print('time:', time()-t)
print('total:', i)  # sancheck
```
Both roughly do the same thing: go through the input file, decompress and parse lines. `pysam` measured 0.1s, and `bamnostic` measured 66s. `samtools view -c` with `/usr/bin/time` gives 0.2s. I have a not yet full-fledged pure python BAM parser script, and it reported ~0.5s. 

I suppose I did something terribly wrong here with bamnostic. What correction would you suggest? Thank you!

**Comment by betteridiot** [comment]
I would have to have the original BAM file to reproduce your results for `bamnostic`. So it is difficult to say what exactly is going on. 

However, `bamnostic` is not meant to be as fast as `pysam` (or `samtools`) and never claims to be (outside of working in a Windows environment). `pysam` operates by interfacing Python with `htslib` directly, which is written in a lower level language and is more performant. The purpose of `bamnostic` is to make bioinformatics analysis of genetic information more accessible.

Additionally, `bamnostic` is doing much more on the initialization steps of iteration such as loading the the bam index file into memory and constructing the objects. This also highlights the other main purpose of `bamnostic`. It was originally written to support random access. Yes. It can iterate through a file top to bottom. But that was not what it was written for.

Using `bamnostic`'s example bam file (`bamnostic.example_bam`), I ran a similar "benchmark" between the two and demonstrate that `bamnostic` is not faster. It just opens up the platforms capable of doing bioinformatic analysis. 
![image](https://user-images.githubusercontent.com/25447319/131583287-ad00365c-1012-4844-a0ab-799e9bda6035.png)

That said, I am excited to read that you are involved (or closely associated) with another pure Python BAM parser. I would love to see it when it gets closer to being published!

**Comment by leaxael** [comment]
Thanks for the swift response and the kind words. I've put the bam file I used for testing at [google drive](https://drive.google.com/file/d/183GTjrFk5ZUhgzr7Z6jxG7ZtuNs7fohG/view?usp=sharing) if you'd like to have a look. It's a little leftover file from an unrelated project. The alignment query is 4 E.coli reference genomes (a couple sequences), the reference is one E.coli genome (2 seqs).

I agree with you that `pysam` is fast. It seems that when just going through bam without specific parsing requirements, a default installation `pysam` is faster than `$ samtools view -c` (conda install or gcc -O3 on the same machine). I haven't got to bench the random access and parsing utilities yet.

A related question - does `htslib` not work on windows desktop/servers using the conda recipe? I've never thought about this until now. Was writing my parser just for fun with no actual usecases.

**Comment by betteridiot** [comment]
As it stands, `htslib` (and by extension, `pysam`) does not work on _native_ Windows. It _can_ work when using Windows Subsystem for Linux (WSL).

However, because the Broad people are very competent, they have deployed some compiled binaries that can install on Windows using `conda` (e.g. `samtools`), but not `htslib` specifically.

The reason `pysam` can work so quickly is because it isn't _really_ doing much on the Python side of things. And since `samtools` runs off the the same `htslib` as `pysam` does, serial access should be just about equivalent.

In the meantime, I will look into the file you posted and see what turns up on my end. Again, I appreciate your enthusiasm on the subject and your reaching out.

**Comment by leaxael** [comment]
Oops sorry, forgot to change the permission when getting the link. Should work now.

Thank you very much for the clarification! I'm not familiar with htslib internals or windows, very interesting to know. I will close this issue, but please feel free to message me if you have questions about the test file. Cheers!

**Comment by betteridiot** [comment]
After sorting and indexing your BAM file, I ran the same benchmark against it (shown below).
![image](https://user-images.githubusercontent.com/25447319/131911124-b0fd7dfd-b5ac-4e67-b70d-9230096c0bd8.png)

You are correct that the process takes a long time for `bamnostic` and that is because of the long read nature of your data. While `bamnostic` can parse the data, it was written with short reads in mind. Because of how byte decoding and long read cigar decoding work, the longer the process becomes an O(n) instead of a constant. 

This is due to the way `bamnostic.core.AlignedSegment._seq_builder()`, `bamnostic.core.AlignedSegment._qual_builder()`, and `bamnostic.core.AlignedSegment._cigar_builder()` (https://github.com/betteridiot/bamnostic/blob/cce37f04bd2c1e63b4af48051245dc021fbd29b9/bamnostic/core.py#L322-L431)

**Comment by leaxael** [comment]
Thank you so much for looking into this! Good to know.
