### ISSUE TITLE
an error when read bam

### ISSUE THREAD

**Issue by Frank1219** [betteridiot/bamnostic#47]
Hi, I think you had done a good job. However, I got an error when used it. Here's my code and the error was 'KeyError: 'None was not found in the file header'. Why does it generate this error, can you fix it as soon as possible ？
![image](https://user-images.githubusercontent.com/14830635/134521940-ae782c0e-59ec-4289-8bf4-b34cf7d55ec9.png)
![Uploading Snipaste_2021-09-23_22-17-09.JPG…]()

**Comment by betteridiot** [comment]
I would have to see the whole traceback to know what is going on. 

Additionally, `bamnostic` does not have complete write support as of yet. There are workarounds, but it isn't fully fleshed out yet.

**Comment by Frank1219** [comment]
![image](https://user-images.githubusercontent.com/14830635/134526360-0aff04a0-624d-47dc-aa04-712880fb996f.png)
I checked it and found that it is generated in the bam.py line 588,  I did not know why you think about it, and please give me some suggestions to fix it, thanks so much.

**Comment by betteridiot** [comment]
Since I do not have access to the BAM file you are using, I will use the `bamnostic.example_bam` included in every build of `bamnostic`.

If I follow your steps (approximately), `bamnostic` is able to create a BAM file with the header from another file:
![image](https://user-images.githubusercontent.com/25447319/134555266-145d887e-363f-45d0-8ea1-886de54614c3.png)

Again, `bamnostic` does not a have a fully implemented write procedure. However, the above suggests that there is a problem with your BAM file's header instead. If this is not the case, or you want to use a fully featured BAM writer, look into `pysam`.

However, thank you for your report as this prompted me to look into working on the write functionality again in the near future.

**Comment by Frank1219** [comment]
Hi, thanks for your reply. I did not upload my data bacuase it is huge. There is a problem with write procedure perhaps, however, the error I found was related with read procedure.
![image](https://user-images.githubusercontent.com/14830635/134601499-622d502d-ad1c-4a2a-a7b7-4a63cbca1647.png)

**Comment by Frank1219** [comment]
I solved this problem by giving a contig id, if possible in the furture, we do not give the contig info, it will scan the whole bam like pysam with fetch method.

**Comment by betteridiot** [comment]
We freely invite pull requests if this is a feature you are looking for! However, `fetch` is meant to be used for random access. If you random access is not required, you can just iterate through the BAM file like a regular file:

```python
import bamnostic as bs

with bs.AlignmentFile('./target.bam') as in_bam:
    for read in in_bam:
        do_something()
```
